from typing import Any, Dict, Optional
from pydantic import BaseModel


class User(BaseModel):
    """
    Represents a user profile with preferences.
    is_synthetic=True means this user was generated by synthetic_data.py
    for ML training — not a real app user.
    """
    id: str
    username: str
    email: Optional[str] = None
    is_synthetic: bool = False
    preferences: Dict[str, Any] = {}